name: Deploy ACR and AKS with Terraform

on:
  workflow_dispatch:

jobs:

  terraform-deployment:
    runs-on: ubuntu-latest
    permissions: write-all
      
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Adjust version as needed

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure the Service Principal is stored in GitHub secrets

      - name: Install Terraform modules
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform deployment
#        env:
#          TF_LOG: TRACE
        run: terraform plan -out=tfplan

      - name: Apply Terraform deployment
        run: terraform apply -auto-approve tfplan

#      - name: Output AKS Cluster Information
#        run: |
#          echo "AKS Cluster kubeconfig:"
#          terraform output kube_config

      - name: Upload Terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: .

      - name: List (repo)
        run: gh variable list
      
      - name: Update last LAST_RUN_ID variable
        run: gh variable set LAST_RUN_ID --body ${{github.run_id}}
