name: Destroy Infrastructure with Terraform

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Adjust version as needed

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure the Service Principal is stored in GitHub secrets

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan
        env:
          TF_VAR_subscription_id: ${{ env.SUBSCRIPTION_ID }}

      - name: Apply Terraform Destroy
        run: terraform apply -auto-approve tfplan