name: Destroy Infrastructure with Terraform

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Terraform state
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          run-id: ${{ env.LAST_RUN_ID }}
          github-token: ${{ secrets.VARIABLE_WRITE_TOKEN }}

#      - name: Azure login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure the Service Principal is stored in GitHub secrets
#
#      - name: Set up Terraform
#        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: 1.4.6  # Adjust version as needed
#
#      - name: Initialize Terraform
#        run: terraform init
#
#      - name: Apply Terraform Destroy
#        run: terraform apply -auto-approve